export const episodes = [
  "Temporada 00/Los Simpsons 0x01 - Buenas Noches.avi",
  "Temporada 00/Los Simpsons 0x02 - Mirando Television.avi",
  "Temporada 00/Los Simpsons 0x03 - Bart Salta.avi",
  "Temporada 00/Los Simpsons 0x04 - Maggie cuida a los Niños.avi",
  "Temporada 00/Los Simpsons 0x05 - El pacifista.avi",
  "Temporada 00/Los Simpsons 0x06 - Competencia de Eruptos.avi",
  "Temporada 00/Los Simpsons 0x07 - Comiendo la Cena.avi",
  "Temporada 00/Los Simpsons 0x08 - Fabricacion de caras.avi",
  "Temporada 00/Los Simpsons 0x09 - El funeral.avi",
  "Temporada 00/Los Simpsons 0x10 - El Cerebro de Maggie.avi",
  "Temporada 00/Los Simpsons 0x11 - Futbol Americano.avi",
  "Temporada 00/Los Simpsons 0x12 - Casa de Cartas.avi",
  "Temporada 00/Los Simpsons 0x13 - Bart y Papa Comiendo.avi",
  "Temporada 00/Los Simpsons 0x14 - Patrulla Espacial.avi",
  "Temporada 00/Los Simpsons 0x15 - Bart y su Corte de Cabello.avi",
  "Temporada 00/Los Simpsons 0x16 - III Guerra Mundial.avi",
  "Temporada 00/Los Simpsons 0x17 - El Crimen Perfecto.avi",
  "Temporada 00/Los Simpsons 0x18 - Historias de Terror.avi",
  "Temporada 00/Los Simpsons 0x19 - El Abuelo y los Niños.avi",
  "Temporada 00/Los Simpsons 0x20 - Fui de Pesca.avi",
  "Temporada 00/Los Simpsons 0x21 - Patinar.avi",
  "Temporada 00/Los Simpsons 0x22 - Los Paganos.avi",
  "Temporada 00/Los Simpsons 0x23 - El Armario.avi",
  "Temporada 00/Los Simpsons 0x24 - El Acuario.avi",
  "Temporada 00/Los Simpsons 0x25 - Retrato Familiar.avi",
  "Temporada 00/Los Simpsons 0x26 - El Paciente Bart.avi",
  "Temporada 00/Los Simpsons 0x27 - El Tarro del Dinero.avi",
  "Temporada 00/Los Simpsons 0x28 - El Museo del Arte.avi",
  "Temporada 00/Los Simpsons 0x29 - Historia del Zoo.avi",
  "Temporada 00/Los Simpsons 0x30 - Cerrar Arriba a Los Simpsons.avi",
  "Temporada 00/Los Simpsons 0x31 - El Juego de Azar.avi",
  "Temporada 00/Los Simpsons 0x32 - El Show de Bart Simpson.avi",
  "Temporada 00/Los Simpsons 0x33 - La Bolsa de Arena.avi",
  "Temporada 00/Los Simpsons 0x34 - Navidad Simpson.avi",
  "Temporada 00/Los Simpsons 0x35 - El Show de Krusty el Payaso.avi",
  "Temporada 00/Los Simpsons 0x36 - Bart el Heroe.avi",
  "Temporada 00/Los Simpsons 0x37 - La Pequeña Fantasia de Bart.avi",
  "Temporada 00/Los Simpsons 0x38 - Pelicula de Terror.avi",
  "Temporada 00/Los Simpsons 0x39 - Casa de la Hipnotizacion.avi",
  "Temporada 00/Los Simpsons 0x40 - El Robar en Tiendas.avi",
  "Temporada 00/Los Simpsons 0x41 - Barranca del Eco.avi",
  "Temporada 00/Los Simpsons 0x42 - Hora de Baño.avi",
  "Temporada 00/Los Simpsons 0x43 - Pesadilla de Bart.avi",
  "Temporada 00/Los Simpsons 0x44 - Bart en la Jungla.avi",
  "Temporada 00/Los Simpsons 0x45 - Terapia Familiar.avi",
  "Temporada 00/Los Simpsons 0x46 - Maggie en Peligro (Parte 1).avi",
  "Temporada 00/Los Simpsons 0x47 - Maggie en Peligro (Parte 2).avi",
  "Temporada 00/Los Simpsons 0x48 - TV Simpson.avi",
  "Temporada 01/Los Simpsons 1x01 - Especial de Navidad de Los Simpsons.flv",
  "Temporada 01/Los Simpsons 1x02 - Bart es un genio.flv",
  "Temporada 01/Los Simpsons 1x03 - La Odisea de Homero.flv",
  "Temporada 01/Los Simpsons 1x04 - Una Familia Modelo.flv",
  "Temporada 01/Los Simpsons 1x05 - El General Bart.flv",
  "Temporada 01/Los Simpsons 1x06 - La depresión de Lisa.flv",
  "Temporada 01/Los Simpsons 1x07 - La llamada de los Simpsons.mp4",
  "Temporada 01/Los Simpsons 1x08 - El héroe sin cabeza.flv",
  "Temporada 01/Los Simpsons 1x09 - Un momento de decisión.mp4",
  "Temporada 01/Los Simpsons 1x10 - La correría de Homero.mp4",
  "Temporada 01/Los Simpsons 1x11 - Intercambio cultural.mp4",
  "Temporada 01/Los Simpsons 1x12 - Krusty va a la cárcel.mp4",
  "Temporada 01/Los Simpsons 1x13 - Una noche encantadora.mp4",
  "Temporada 02/Los Simpsons 2x01 - Bart reprueba.mp4",
  "Temporada 02/Los Simpsons 2x02 - Simpson y Dalila.mp4",
  "Temporada 02/Los Simpsons 2x03 - Especial de noche de brujas de los Simpsons.mp4",
  "Temporada 02/Los Simpsons 2x04 - Dos Autos en Cada Garage, Tres Ojos en Cada Pez.mp4",
  "Temporada 02/Los Simpsons 2x05 - Homero el animador.mp4",
  "Temporada 02/Los Simpsons 2x06 - La sociedad de los golfistas muertos.mp4",
  "Temporada 02/Los Simpsons 2x07 - Bart contra el día de gracias.mp4",
  "Temporada 02/Los Simpsons 2x08 - Bart el temerario.mp4",
  "Temporada 02/Los Simpsons 2x09 - Tomy, Daly y Marge.mp4",
  "Temporada 02/Los Simpsons 2x10 - Bart es atropellado.mp4",
  "Temporada 02/Los Simpsons 2x11 - Aviso de muerte.mp4",
  "Temporada 02/Los Simpsons 2x12 - Los años que vivimos.mp4",
  "Temporada 02/Los Simpsons 2x13 - No robarás.mp4",
  "Temporada 02/Los Simpsons 2x14 - El último tren.mp4",
  "Temporada 02/Los Simpsons 2x15 - Dónde estás, hermano mío.mp4",
  "Temporada 02/Los Simpsons 2x16 - El perro de Bart reprueba.mp4",
  "Temporada 02/Los Simpsons 2x17 - Nuestros años felices.mp4",
  "Temporada 02/Los Simpsons 2x18 - Pinceles con Grandeza.mp4",
  "Temporada 02/Los Simpsons 2x19 - El Sustituto de Lisa.mp4",
  "Temporada 02/Los Simpsons 2x20 - La Guerra de los Simpsons.flv",
  "Temporada 02/Los Simpsons 2x21 - Tres Hombres y una Historieta.mp4",
  "Temporada 02/Los Simpsons 2x22 - Sangre Nueva.flv",
  "Temporada 03/Los Simpsons 3x01 - Papá está Loco.flv",
  "Temporada 03/Los Simpsons 3x02 - Lisa va a Washington.flv",
  "Temporada 03/Los Simpsons 3x03 - El día que cayó Flanders.flv",
  "Temporada 03/Los Simpsons 3x04 - El pequeño Padrino.flv",
  "Temporada 03/Los Simpsons 3x05 - Homero en el Diccionario.flv",
  "Temporada 03/Los Simpsons 3x06 - De tal padre, tal payaso.flv",
  "Temporada 03/Los Simpsons 3x07 - Especial de Noche de Brujas II.flv",
  "Temporada 03/Los Simpsons 3x08 - El pony de Lisa.flv",
  "Temporada 03/Los Simpsons 3x09 - Tardes de Trueno.mp4",
  "Temporada 03/Los Simpsons 3x10 - Llamarada Moe.flv",
  "Temporada 03/Los Simpsons 3x11 - Burns y los alemanes.flv",
  "Temporada 03/Los Simpsons 3x12 - Me casé con Marge.mp4",
  "Temporada 03/Los Simpsons 3x13 - Bart y la Radio.flv",
  "Temporada 03/Los Simpsons 3x14 - Los pronósticos de Lisa.flv",
  "Temporada 03/Los Simpsons 3x15 - Homero se queda Solo.flv",
  "Temporada 03/Los Simpsons 3x16 - Bart el Amante.flv",
  "Temporada 03/Los Simpsons 3x17 - Homero y el Bat.flv",
  "Temporada 03/Los Simpsons 3x18 - Vocaciones Distintas.flv",
  "Temporada 03/Los Simpsons 3x19 - Nuestro mejor amigo.flv",
  "Temporada 03/Los Simpsons 3x20 - Homero el campirano.flv",
  "Temporada 03/Los Simpsons 3x21 - El viudo negro.flv",
  "Temporada 03/Los Simpsons 3x22 - El rock de Otto.flv",
  "Temporada 03/Los Simpsons 3x23 - Milhouse se enamora.flv",
  "Temporada 03/Los Simpsons 3x24 - Él es mi Hermano.mp4",
  "Temporada 04/Los Simpsons 4x01 - Campo Krusty.flv",
  "Temporada 04/Los Simpsons 4x02 - Un tranvía llamado Marge.flv",
  "Temporada 04/Los Simpsons 4x03 - Homero hereje.flv",
  "Temporada 04/Los Simpsons 4x04 - La reina de la belleza.flv",
  "Temporada 04/Los Simpsons 4x05 - Especial de Noche de Brujas III.flv",
  "Temporada 04/Los Simpsons 4x06 - Tomy & Daly (La Película).flv",
  "Temporada 04/Los Simpsons 4x07 - Marge Consigue Empleo.mp4",
  "Temporada 04/Los Simpsons 4x08 - La Chica Nueva.flv",
  "Temporada 04/Los Simpsons 4x09 - Don Barredora.flv",
  "Temporada 04/Los Simpsons 4x10 - La primera palabra de Maggie.flv",
  "Temporada 04/Los Simpsons 4x11 - El Gran Corazon de Homero.mp4",
  "Temporada 04/Los Simpsons 4x12 - Marge contra el monorriel.flv",
  "Temporada 04/Los Simpsons 4x13 - La elección de Selma.flv",
  "Temporada 04/Los Simpsons 4x14 - Hermano mayor, Hermano menor.mp4",
  "Temporada 04/Los Simpsons 4x15 - Yo amo a Lisa.mp4",
  "Temporada 04/Los Simpsons 4x16 - La Promesa.mp4",
  "Temporada 04/Los Simpsons 4x17 - La última salida a Springfield.mp4",
  "Temporada 04/Los Simpsons 4x18 - A esto hemos llegado.mp4",
  "Temporada 04/Los Simpsons 4x19 - El intermedio.flv",
  "Temporada 04/Los Simpsons 4x20 - El día del Garrote.mp4",
  "Temporada 04/Los Simpsons 4x21 - Marge en cadenas.flv",
  "Temporada 04/Los Simpsons 4x22 - El drama de Krusty.mp4",
  "Temporada 05/Los Simpsons 5x01 - El cuarteto de Homero.flv",
  "Temporada 05/Los Simpsons 5x02 - Cabo de miedosos.mp4",
  "Temporada 05/Los Simpsons 5x03 - Homero va a la universidad.flv",
  "Temporada 05/Los Simpsons 5x04 - El oso de Burns.mp4",
  "Temporada 05/Los Simpsons 5x05 - Especial de Noche de Brujas IV.flv",
  "Temporada 05/Los Simpsons 5x06 - Marge la rebelde.flv",
  "Temporada 05/Los Simpsons 5x07 - Filosofía Bartiana.flv",
  "Temporada 05/Los Simpsons 5x08 - Exploradores a la Fuerza.mp4",
  "Temporada 05/Los Simpsons 5x09 - La última tentación de Homero.flv",
  "Temporada 05/Los Simpsons 5x10 - Springfield prospero o el problema del juego.mp4",
  "Temporada 05/Los Simpsons 5x11 - Homero detective.flv",
  "Temporada 05/Los Simpsons 5x12 - Bart se hace famoso.mp4",
  "Temporada 05/Los Simpsons 5x13 - Homero y Apu.mp4",
  "Temporada 05/Los Simpsons 5x14 - Lisa contra la Baby Malibu.mp4",
  "Temporada 05/Los Simpsons 5x15 - Homero en el espacio profundo.flv",
  "Temporada 05/Los Simpsons 5x16 - Homero ama a Flanders.mp4",
  "Temporada 05/Los Simpsons 5x17 - Bart gana un elefante.flv",
  "Temporada 05/Los Simpsons 5x18 - El heredero de Burns.mp4",
  "Temporada 05/Los Simpsons 5x19 - La canción de Skinner.flv",
  "Temporada 05/Los Simpsons 5x20 - El niño que sabia demasiado.mp4",
  "Temporada 05/Los Simpsons 5x21 - El amante de Lady Bouvier.flv",
  "Temporada 05/Los Simpsons 5x22 - Secretos de un buen matrimonio.flv",
  "Temporada 06/Los Simpsons 6x01 - El diabólico Bart.mp4",
  "Temporada 06/Los Simpsons 6x02 - La rival de Lisa.flv",
  "Temporada 06/Los Simpsons 6x03 - Recuerdos de Amor.flv",
  "Temporada 06/Los Simpsons 6x04 - La tierra de Tomy & Daly.flv",
  "Temporada 06/Los Simpsons 6x05 - El Regreso de Bob Patiño.mp4",
  "Temporada 06/Los Simpsons 6x06 - Especial de Noche de Brujas V.flv",
  "Temporada 06/Los Simpsons 6x07 - La novia de Bart.mp4",
  "Temporada 06/Los Simpsons 6x08 - Lisa y los deportes.flv",
  "Temporada 06/Los Simpsons 6x09 - Homero el Malo.mp4",
  "Temporada 06/Los Simpsons 6x10 - El Abuelo y la ineficiencia romántica.flv",
  "Temporada 06/Los Simpsons 6x11 - Miedo a volar.flv",
  "Temporada 06/Los Simpsons 6x12 - Homero el Grande.mp4",
  "Temporada 06/Los Simpsons 6x13 - Y con Maggie son Tres.mp4",
  "Temporada 06/Los Simpsons 6x14 - El cometa de Bart.flv",
  "Temporada 06/Los Simpsons 6x15 - Homie el payaso.flv",
  "Temporada 06/Los Simpsons 6x16 - Bart contra Australia.mp4",
  "Temporada 06/Los Simpsons 6x17 - Homero contra Patty.mp4",
  "Temporada 06/Los Simpsons 6x18 - Una estrella estrellada.flv",
  "Temporada 06/Los Simpsons 6x19 - La boda de Lisa.mp4",
  "Temporada 06/Los Simpsons 6x20 - Un galgo llamado Monty.flv",
  "Temporada 06/Los Simpsons 6x21 - Lucha Educativa.mp4",
  "Temporada 06/Los Simpsons 6x22 - Por la ciudad de Springfield.mp4",
  "Temporada 06/Los Simpsons 6x23 - Contacto en Springfield.flv",
  "Temporada 06/Los Simpsons 6x24 - El Limon de Troya.mp4",
  "Temporada 06/Los Simpsons 6x25 - Quién mató al señor Burns - I parte.flv",
  "Temporada 07/Los Simpsons 7x01 - Quién mató al señor Burns - II parte.mp4",
  "Temporada 07/Los Simpsons 7x02 - El Hombre Radioactivo.mp4",
  "Temporada 07/Los Simpsons 7x03 - Hogar dulce hogarcirijillo.mp4",
  "Temporada 07/Los Simpsons 7x04 - Bart vende su alma.flv",
  "Temporada 07/Los Simpsons 7x05 - Lisa la Vegetariana.mp4",
  "Temporada 07/Los Simpsons 7x06 - Especial de Noche de Brujas VI.mp4",
  "Temporada 07/Los Simpsons 7x07 - Homero tamaño familiar.flv",
  "Temporada 07/Los Simpsons 7x08 - Mamá Simpsons.mp4",
  "Temporada 07/Los Simpsons 7x09 - La Ultima Carcajada de Bob Patiño.mp4",
  "Temporada 07/Los Simpsons 7x10 - El Episodio Espectacular 138 de los Simpson.flv",
  "Temporada 07/Los Simpsons 7x11 - El bebe de Mamá.mp4",
  "Temporada 07/Los Simpsons 7x12 - El Equipo de Homero.mp4",
  "Temporada 07/Los Simpsons 7x13 - El Mal Vecino.mp4",
  "Temporada 07/Los Simpsons 7x14 - Lucha de clases en Springfield.mp4",
  "Temporada 07/Los Simpsons 7x15 - Bart el soplón.flv",
  "Temporada 07/Los Simpsons 7x16 - Lisa la Iconoclasta.mp4",
  "Temporada 07/Los Simpsons 7x17 - Homero Smithers.flv",
  "Temporada 07/Los Simpsons 7x18 - El Día que murió la Violencia.mp4",
  "Temporada 07/Los Simpsons 7x19 - El sueño de amor de Selma.mp4",
  "Temporada 07/Los Simpsons 7x20 - Bart recorre el Mundo.mp4",
  "Temporada 07/Los Simpsons 7x21 - 22 películas cortas sobre Springfield.mp4",
  "Temporada 07/Los Simpsons 7x22 - Mi héroe, el Abuelo.flv",
  "Temporada 07/Los Simpsons 7x23 - Y Donde esta el Inmigrante.mp4",
  "Temporada 07/Los Simpsons 7x24 - Reventón.flv",
  "Temporada 07/Los Simpsons 7x25 - Yo amo a Lisa.mp4",
  "Temporada 08/Los Simpsons 8x01 - Especial de Noche de Brujas VII.mp4",
  "Temporada 08/Los Simpsons 8x02 - Solo se muda dos veces.mp4",
  "Temporada 08/Los Simpsons 8x03 - Homero por el Campeonato.mp4",
  "Temporada 08/Los Simpsons 8x04 - Papi Burns.mp4",
  "Temporada 08/Los Simpsons 8x05 - Bart de Noche.mp4",
  "Temporada 08/Los Simpsons 8x06 - Milhouse Dividido.mp4",
  "Temporada 08/Los Simpsons 8x07 - El soso romance de Lisa.mp4",
  "Temporada 08/Los Simpsons 8x08 - Huracán Neddy.mp4",
  "Temporada 08/Los Simpsons 8x09 - El viaje misterioso de nuestro Homero.flv",
  "Temporada 08/Los Simpsons 8x10 - Los Expedientes secretos de Springfield.mp4",
  "Temporada 08/Los Simpsons 8x11 - El turbio y oscuro mundo de Marge Simpson.mp4",
  "Temporada 08/Los Simpsons 8x12 - La Montaña de la locura.flv",
  "Temporada 08/Los Simpsons 8x13 - Simpsoncalifragilisticoexpialeroso.mp4",
  "Temporada 08/Los Simpsons 8x14 - El espectáculo de Tomy, Daly y Poochie.mp4",
  "Temporada 08/Los Simpsons 8x15 - La fobia de Homero.mp4",
  "Temporada 08/Los Simpsons 8x16 - El hermano de otra seria.mp4",
  "Temporada 08/Los Simpsons 8x17 - Niñera y hermana.flv",
  "Temporada 08/Los Simpsons 8x18 - Homero contra la prohibición.mp4",
  "Temporada 08/Los Simpsons 8x19 - Amor en la escuela.mp4",
  "Temporada 08/Los Simpsons 8x20 - Motín Canino.mp4",
  "Temporada 08/Los Simpsons 8x21 - El viejo y la Lisa.mp4",
  "Temporada 08/Los Simpsons 8x22 - Pregúntale a Marge.mp4",
  "Temporada 08/Los Simpsons 8x23 - El enemigo de Homero.mp4",
  "Temporada 08/Los Simpsons 8x24 - El repertorio de refritos de Los Simpsons.mp4",
  "Temporada 08/Los Simpsons 8x25 - La guerra secreta de Lisa Simpson.mp4",
  "Temporada 09/Los Simpsons 9x01 - La ciudad de Nueva York contra Homero.mp4",
  "Temporada 09/Los Simpsons 9x02 - Vida Prestada.mp4",
  "Temporada 09/Los Simpsons 9x03 - El Sax de Lisa.mp4",
  "Temporada 09/Los Simpsons 9x04 - Especial de Noche de Brujas VIII.mp4",
  "Temporada 09/Los Simpsons 9x05 - Familia peligrosa.flv",
  "Temporada 09/Los Simpsons 9x06 - Bart se convierte en estrella.mp4",
  "Temporada 09/Los Simpsons 9x07 - Las dos señoras Nahasapeemapetilon.mp4",
  "Temporada 09/Los Simpsons 9x08 - La escéptica Lisa.mp4",
  "Temporada 09/Los Simpsons 9x09 - La Cruda realidad.mp4",
  "Temporada 09/Los Simpsons 9x10 - Milagro en la Avenida Siempreviva.mp4",
  "Temporada 09/Los Simpsons 9x11 - Todos cantan, todos bailan.mp4",
  "Temporada 09/Los Simpsons 9x12 - Bart en la feria.mp4",
  "Temporada 09/Los Simpsons 9x13 - La secta Simpson.mp4",
  "Temporada 09/Los Simpsons 9x14 - El Autobus de la muerte.mp4",
  "Temporada 09/Los Simpsons 9x15 - La última tentación de Krusty.mp4",
  "Temporada 09/Los Simpsons 9x16 - El bueno, la mala y el feo.mp4",
  "Temporada 09/Los Simpsons 9x17 - Lisa, Simpson.mp4",
  "Temporada 09/Los Simpsons 9x18 - Gorgorito.flv",
  "Temporada 09/Los Simpsons 9x19 - Mi querido capitán Simpson.mp4",
  "Temporada 09/Los Simpsons 9x20 - Mision Deducible.mp4",
  "Temporada 09/Los Simpsons 9x21 - Lisa comentarista.mp4",
  "Temporada 09/Los Simpsons 9x22 - Basura de Titanes.flv",
  "Temporada 09/Los Simpsons 9x23 - El rey de la colina.mp4",
  "Temporada 09/Los Simpsons 9x24 - Hemos perdido a nuestra Lisa.mp4",
  "Temporada 09/Los Simpsons 9x25 - Marge, ¿puedo dormir con el peligro.flv",
  "Temporada 10/Los Simpsons 10x01 - La sazón del Baile.mp4",
  "Temporada 10/Los Simpsons 10x02 - El mago de la terraza por Siempre verde.mp4",
  "Temporada 10/Los Simpsons 10x03 - Bart La Madre.mp4",
  "Temporada 10/Los Simpsons 10x04 - Especial de Dia de Brujas IX  (El Arbol del Horror 9).mp4",
  "Temporada 10/Los Simpsons 10x05 - Cuando se anhela a una estrella.mp4",
  "Temporada 10/Los Simpsons 10x06 - Ough en el viento.mp4",
  "Temporada 10/Los Simpsons 10x07 - Lisa obtiene un 10.mp4",
  `Temporada 10/Los Simpsons 10x08 - Homero Simpson en 'Problemas renales'.mp4`,
  "Temporada 10/Los Simpsons 10x09 - Encuentro con la mafia.mp4",
  "Temporada 10/Los Simpsons 10x10 - Viva Ned Flanders.mp4",
  "Temporada 10/Los Simpsons 10x11 - A un Bart salvaje nadie puede destrozarlo.mp4",
  "Temporada 10/Los Simpsons 10x12 - Domingo, Cruel Domingo.flv",
  "Temporada 10/Los Simpsons 10x13 - Homero al Máximo.mp4",
  "Temporada 10/Los Simpsons 10x14 - Me Acompaña Cupido.flv",
  "Temporada 10/Los Simpsons 10x15 - El Submarino Amarillo.mp4",
  "Temporada 10/Los Simpsons 10x16 - Hagan lugar para Lisa.flv",
  "Temporada 10/Los Simpsons 10x17 - Homero Trabaja Demasiado.flv",
  "Temporada 10/Los Simpsons 10x18 - Historias de la Biblia.mp4",
  "Temporada 10/Los Simpsons 10x19 - Arte de Mamá y Papá.flv",
  "Temporada 10/Los Simpsons 10x20 - El Anciano y el Estudiante con Malas Calificaciones.mp4",
  "Temporada 10/Los Simpsons 10x21 - Monty no Puede Comprarme Amor.mp4",
  "Temporada 10/Los Simpsons 10x22 - Salvaron el cerebro de Lisa.flv",
  "Temporada 10/Los Simpsons 10x23 - Treinta Minutos sobre Tokio.mp4",
  "Temporada 11/Los Simpsons 11x01 - Homero va a Hollywood.mp4",
  "Temporada 11/Los Simpsons 11x02 - El cambio de Bart.flv",
  "Temporada 11/Los Simpsons 11x03 - Adivina quién viene a criticar.mp4",
  "Temporada 11/Los Simpsons 11x04 - Especial de Noche de Brujas X.flv",
  "Temporada 11/Los Simpsons 11x05 - Homero Granjero.mp4",
  "Temporada 11/Los Simpsons 11x06 - Hola Mamá, Hola Papá.flv",
  "Temporada 11/Los Simpsons 11x07 - Mal Comportamiento.flv",
  "Temporada 11/Los Simpsons 11x08 -  Llévate a mi esposa.flv",
  "Temporada 11/Los Simpsons 11x09 - Un Gran Embaucador.mp4",
  "Temporada 11/Los Simpsons 11x10 - La Pequeña Mamá.flv",
  "Temporada 11/Los Simpsons 11x11 - Perdida de Fé.mp4",
  "Temporada 11/Los Simpsons 11x12 - La Familia Mansión.mp4",
  "Temporada 11/Los Simpsons 11x13 - Jinetes Galácticos.flv",
  "Temporada 11/Los Simpsons 11x14 - Solo Nuevamentirijillo.mp4",
  "Temporada 11/Los Simpsons 11x15 - Misionero- Imposible.mp4",
  "Temporada 11/Los Simpsons 11x16 - Pigmoelion.flv",
  "Temporada 11/Los Simpsons 11x17 - Bart al Futuro.mp4",
  "Temporada 11/Los Simpsons 11x18 - Dias de Vino y Rosas.mp4",
  "Temporada 11/Los Simpsons 11x19 - Mata al cocodrilo y huye.flv",
  "Temporada 11/Los Simpsons 11x20 - El último Tango en Springfield.flv",
  "Temporada 11/Los Simpsons 11x21 - Marge esta loca, loca, loca.flv",
  "Temporada 11/Los Simpsons 11x22 - Detrás de la Risa.flv",
  "Temporada 12/Los Simpsons 12x01 - Especial de Noche de Brujas XI.flv",
  "Temporada 12/Los Simpsons 12x02 - El Cuento de dos Ciudades.mp4",
  "Temporada 12/Los Simpsons 12x03 - El Payaso Demente.mp4",
  "Temporada 12/Los Simpsons 12x04 - Lisa y su Amor por Los Arboles.mp4",
  "Temporada 12/Los Simpsons 12x05 - Homero contra la Dignidad.mp4",
  "Temporada 12/Los Simpsons 12x06 - Amenaza informática.flv",
  "Temporada 12/Los Simpsons 12x07 - El Gran Estafador.mp4",
  "Temporada 12/Los Simpsons 12x08 - Skinner cubierto por la Nieve.mp4",
  "Temporada 12/Los Simpsons 12x09 - Homero.mp4",
  "Temporada 12/Los Simpsons 12x10 - Pokemamá.flv",
  "Temporada 12/Los Simpsons 12x11 - El Peor Episodio de la Serie.flv",
  "Temporada 12/Los Simpsons 12x12 - Juego Limpio.mp4",
  "Temporada 12/Los Simpsons 12x13 - El día de la muerte de la Comedia.flv",
  "Temporada 12/Los Simpsons 12x14 - Idolos.mp4",
  "Temporada 12/Los Simpsons 12x15 - Homero Idealista.mp4",
  "Temporada 12/Los Simpsons 12x16 - Los Motivos del Abusón.flv",
  "Temporada 12/Los Simpsons 12x17 - Safari Simpson.mp4",
  "Temporada 12/Los Simpsons 12x18 - Trilogía del Error.mp4",
  "Temporada 12/Los Simpsons 12x19 - Veneración a la Homero.mp4",
  "Temporada 12/Los Simpsons 12x20 - Hijos de Segunda Clase.flv",
  "Temporada 12/Los Simpsons 12x21 - Relatos Extraordinarios.mp4",
  "Temporada 13/Los Simpsons 13x01 - Especial de Dia de Brujas XII.mp4",
  "Temporada 13/Los Simpsons 13x02 - Padres e Hijos.flv",
  "Temporada 13/Los Simpsons 13x03 - La Taberna de Homero.mp4",
  "Temporada 13/Los Simpsons 13x04 - El Sr Burns se Enamora.mp4",
  "Temporada 13/Los Simpsons 13x05 - Recuerdos de Infancia.flv",
  "Temporada 13/Los Simpsons 13x06 - Lisa de Poca Fe.mp4",
  "Temporada 13/Los Simpsons 13x07 - Conflictos Familiares.mp4",
  "Temporada 13/Los Simpsons 13x08 - La Agridulce Marge.mp4",
  "Temporada 13/Los Simpsons 13x09 - Mandíbula bien Cerrada.flv",
  "Temporada 13/Los Simpsons 13x10 - Una Proposición un poco Indecorosa.mp4",
  "Temporada 13/Los Simpsons 13x11 - Bart se Enamora.flv",
  "Temporada 13/Los Simpsons 13x12 - El Ultimo Vaquero del Oeste.mp4",
  "Temporada 13/Los Simpsons 13x13 - Cuentos del Dominio Publico.mp4",
  "Temporada 13/Los Simpsons 13x14 - El Viejo y el Amar.mp4",
  "Temporada 13/Los Simpsons 13x15 - La culpa es de Lisa.mp4",
  "Temporada 13/Los Simpsons 13x16 - Fin de Semana con Burns.flv",
  "Temporada 13/Los Simpsons 13x17 - Homenaje a Homero.mp4",
  "Temporada 13/Los Simpsons 13x18 - Estoy Furioso.mp4",
  "Temporada 13/Los Simpsons 13x19 - El Dulce Apu.mp4",
  "Temporada 13/Los Simpsons 13x20 - La pequeña Lisa y los Diez Grandes.mp4",
  "Temporada 13/Los Simpsons 13x21 - El Juego de la Muerte.mp4",
  "Temporada 13/Los Simpsons 13x22 - Papá Tiene una Placa Nueva.mp4",
  "Temporada 14/Los Simpsons 14x01 - La Decimotercera casa del horror de Los Simpson.mp4",
  "Temporada 14/Los Simpsons 14x02 - Cómo Pasé mis Vacaciones de Verano.mp4",
  "Temporada 14/Los Simpsons 14x03 - Bart contra Lisa Contra el Tercer Año.mp4",
  "Temporada 14/Los Simpsons 14x04 - Las Curvas de Marge.mp4",
  "Temporada 14/Los Simpsons 14x05 - Un Nuevo Hogar.flv",
  "Temporada 14/Los Simpsons 14x06 - El Gran Detective Criminal.mp4",
  "Temporada 14/Los Simpsons 14x07 - Edna Especial.mp4",
  "Temporada 14/Los Simpsons 14x08 - El Padre que Sabía Muy Poco.mp4",
  "Temporada 14/Los Simpsons 14x09 - Los Brazos Fuertes de Mamá.flv",
  "Temporada 14/Los Simpsons 14x10 - Pide Cualquier Cosa.mp4",
  "Temporada 14/Los Simpsons 14x11 - Emancipación.mp4",
  "Temporada 14/Los Simpsons 14x12 - La Encrucijada de Lisa.mp4",
  "Temporada 14/Los Simpsons 14x13 - Nace una Nueva Estrella.mp4",
  "Temporada 14/Los Simpsons 14x14 - Krusty va a Washington.flv",
  "Temporada 14/Los Simpsons 14x15 - El Presidente.mp4",
  "Temporada 14/Los Simpsons 14x16 - Reencuentro Con el Firmamento.mp4",
  "Temporada 14/Los Simpsons 14x17 - Tres gays en un Condominio.mp4",
  "Temporada 14/Los Simpsons 14x18 - Dónde está mi Rancho.mp4",
  "Temporada 14/Los Simpsons 14x19 - El Perro Cobarde.mp4",
  "Temporada 14/Los Simpsons 14x20 - Detengan a mi Esposa, Por Favor.mp4",
  "Temporada 14/Los Simpsons 14x21 - La Guerra de Bart.mp4",
  "Temporada 14/Los Simpsons 14x22 - Moe se Convierte en Niñera.mp4",
  "Temporada 15/Los Simpsons 15x01 - La Casita del Horror XIV.mp4",
  "Temporada 15/Los Simpsons 15x02 - Mi Madre la Robacoches.mp4",
  "Temporada 15/Los Simpsons 15x03 - La Presidenta usaba Perlas.mp4",
  "Temporada 15/Los Simpsons 15x04 - Los Monólogos de la Reina.mp4",
  "Temporada 15/Los Simpsons 15x05 - El Gordo y el Peludo.mp4",
  "Temporada 15/Los Simpsons 15x06 - Hoy, Soy un Payaso.mp4",
  "Temporada 15/Los Simpsons 15x07 - La Decimoquinta Temporada.mp4",
  "Temporada 15/Los Simpsons 15x08 - Marge Contra los Solteros, Adultos Mayores, Parejas sin Hijos, Adolescentes y Gays.mp4",
  "Temporada 15/Los Simpsons 15x09 - Yo, Robot.mp4",
  "Temporada 15/Los Simpsons 15x10 - Sátira de un Ama de Casa Fastidiada.mp4",
  "Temporada 15/Los Simpsons 15x11 - El Recorrido Histórico de Marge.mp4",
  "Temporada 15/Los Simpsons 15x12 - Milhouse Ya no Vive Aquí.mp4",
  "Temporada 15/Los Simpsons 15x13 - Lista y más Lista.flv",
  "Temporada 15/Los Simpsons 15x14 - Artie Ziff Viene a Cenar.mp4",
  "Temporada 15/Los Simpsons 15x15 - El Día de La Co-dependencia.mp4",
  "Temporada 15/Los Simpsons 15x16 - El Delincuente Errante.flv",
  "Temporada 15/Los Simpsons 15x17 - El Día de mi Boda.mp4",
  "Temporada 15/Los Simpsons 15x18 - Atrápalos si Puedes.flv",
  "Temporada 15/Los Simpsons 15x19 - El Simple Simpson.mp4",
  "Temporada 15/Los Simpsons 15x20 - Nuestros Años Infelices.mp4",
  "Temporada 15/Los Simpsons 15x21 - La Bandera de Bart.mp4",
  "Temporada 15/Los Simpsons 15x22 - Noticias Engañosas.mp4",
  "Temporada 16/Los Simpsons 16x01 - La Casita del Horror XV.mp4",
  "Temporada 16/Los Simpsons 16x02 - En La Guerra Todo se Vale.mp4",
  "Temporada 16/Los Simpsons 16x03 - Durmiendo Con el Enemigo.flv",
  "Temporada 16/Los Simpsons 16x04 - Ella era Mi Amiga.mp4",
  "Temporada 16/Los Simpsons 16x05 - El Gordo y el Niñito.mp4",
  "Temporada 16/Los Simpsons 16x06 - Receta de Medianoche.mp4",
  "Temporada 16/Los Simpsons 16x07 - La Señorita Cerveza.mp4",
  "Temporada 16/Los Simpsons 16x08 - La Jugada Desesperada de Homero y Ned.mp4",
  "Temporada 16/Los Simpsons 16x09 - El Rap del Bromista.mp4",
  "Temporada 16/Los Simpsons 16x10 - El Amor es Ciego.mp4",
  "Temporada 16/Los Simpsons 16x11 - Lejos de Mi Hermana.mp4",
  "Temporada 16/Los Simpsons 16x12 - Aventura en China.mp4",
  "Temporada 16/Los Simpsons 16x13 - La Casa Rodante de Homero.mp4",
  "Temporada 16/Los Simpsons 16x14 - El Informante.mp4",
  "Temporada 16/Los Simpsons 16x15 - Futurdrama.flv",
  "Temporada 16/Los Simpsons 16x16 - Ray El Contratista.mp4",
  "Temporada 16/Los Simpsons 16x17 - El Niño del Corazón Roto.flv",
  "Temporada 16/Los Simpsons 16x18 - Una Estrellita Estrellada.flv",
  "Temporada 16/Los Simpsons 16x19 - El Día del Juicio.mp4",
  "Temporada 16/Los Simpsons 16x20 - Un Hogar Lejos de Homero.flv",
  "Temporada 16/Los Simpsons 16x21 - El Padre, El Hijo, y La Santa Estrella Invitada.mp4",
  "Temporada 17/Los Simpsons 17x01 - La Hoguera de Los Manatíes.flv",
  "Temporada 17/Los Simpsons 17x02 - La Niña que Dormía Muy Poco.mp4",
  "Temporada 17/Los Simpsons 17x03 - Milhouse de Arena y Niebla.mp4",
  "Temporada 17/Los Simpsons 17x04 - La Casita del Horror XVI.mp4",
  "Temporada 17/Los Simpsons 17x05 - El Envenenamiento del hijo de Marge.flv",
  "Temporada 17/Los Simpsons 17x06 - Homero se Postula.mp4",
  "Temporada 17/Los Simpsons 17x07 - Los dulces Tomates Rojos.flv",
  "Temporada 17/Los Simpsons 17x08 - Bob el Italiano.mp4",
  "Temporada 17/Los Simpsons 17x09 - Historia de Navidad de Los Simpsons.mp4",
  "Temporada 17/Los Simpsons 17x10 - El padre de Homero.flv",
  "Temporada 17/Los Simpsons 17x11 - En el Camino a Ninguna Parte.mp4",
  "Temporada 17/Los Simpsons 17x12 - Mi Bello Jardinero.flv",
  "Temporada 17/Los Simpsons 17x13 - Historia Aparentemente sin Final.mp4",
  "Temporada 17/Los Simpsons 17x14 - Bart Tiene dos Mamás.flv",
  "Temporada 17/Los Simpsons 17x15 - Homero Simpson, ésta es tu Esposa.mp4",
  "Temporada 17/Los Simpsons 17x16 - El Abuelo del millón de Dólares.flv",
  "Temporada 17/Los Simpsons 17x17 - Adiós a la India.mp4",
  "Temporada 17/Los Simpsons 17x18 - Las Historias más Mojadas Jamás Contadas.flv",
  "Temporada 17/Los Simpsons 17x19 - Las Chicas sólo Quieren Sumar.mp4",
  "Temporada 17/Los Simpsons 17x20 - Hablando de Marge.mp4",
  "Temporada 17/Los Simpsons 17x21 - El Traje de Simio.mp4",
  "Temporada 17/Los Simpsons 17x22 - Juego de Parejas con Marge y Homero.mp4",
  "Temporada 18/Los Simpsons 18x01 - El Niño, el Chef, la Esposa y su Homero.mp4",
  "Temporada 18/Los Simpsons 18x02 - Jazzy y Los Gatitos.mp4",
  "Temporada 18/Los Simpsons 18x03 - Por favor Homero, no uses el Martillo.flv",
  "Temporada 18/Los Simpsons 18x04 - La Casita de los Horrores XVII.mp4",
  "Temporada 18/Los Simpsons 18x05 - Homero en el Ejército.flv",
  "Temporada 18/Los Simpsons 18x06 - Moe y Lisa.mp4",
  "Temporada 18/Los Simpsons 18x07 - Helado de marge (La del cabello azul claro).mp4",
  "Temporada 18/Los Simpsons 18x08 - Extraña Pareja.mp4",
  "Temporada 18/Los Simpsons 18x09 - Maten a Gil, Vol I y II.flv",
  "Temporada 18/Los Simpsons 18x10 - La Esposa Acuática.mp4",
  "Temporada 18/Los Simpsons 18x11 - La Venganza es un Platillo que se Sirve Tres veces.flv",
  "Temporada 18/Los Simpsons 18x12 - Pequeña niña Grande.flv",
  "Temporada 18/Los Simpsons 18x13 - Creciendo en Springfield.mp4",
  "Temporada 18/Los Simpsons 18x14 - Canción Rural.mp4",
  "Temporada 18/Los Simpsons 18x15 - El Viejo Romeo y la Nueva Julieta.flv",
  "Temporada 18/Los Simpsons 18x16 - Homerazzi.mp4",
  "Temporada 18/Los Simpsons 18x17 - Juegos Familiares.mp4",
  "Temporada 18/Los Simpsons 18x18 - El Gran Perdedor.flv",
  "Temporada 18/Los Simpsons 18x19 - Pillos con Escaleras.mp4",
  "Temporada 18/Los Simpsons 18x20 - Para o mi Perro Dispara.flv",
  "Temporada 18/Los Simpsons 18x21 - 24 Minutos.mp4",
  "Temporada 18/Los Simpsons 18x22 - No Siempre Puedes Decir lo que Quieres.flv",
  "Temporada 19/Los Simpsons 19x01 - Le Gusta Volar y se Nota.mp4",
  "Temporada 19/Los Simpsons 19x02 - Homero de Sevilla.flv",
  "Temporada 19/Los Simpsons 19x03 - Grúa de Medianoche.mp4",
  "Temporada 19/Los Simpsons 19x04 - Una Media Mañana de Perros.flv",
  "Temporada 19/Los Simpsons 19x05 - La casita del Horror XVIII.flv",
  "Temporada 19/Los Simpsons 19x06 - Milito el Huerfanito.mp4",
  "Temporada 19/Los Simpsons 19x07 - Esposos y Bisturís.flv",
  "Temporada 19/Los Simpsons 19x08 - Funeral Para un Enemigo.mp4",
  "Temporada 19/Los Simpsons 19x09 - Eterna Penumbra de la mente Simpson.mp4",
  "Temporada 19/Los Simpsons 19x10 - Rafa Gorgory Electivo.mp4",
  "Temporada 19/Los Simpsons 19x11 - El show de los años 90.flv",
  "Temporada 19/Los Simpsons 19x12 - Amor al Estilo de Springfield.mp4",
  "Temporada 19/Los Simpsons 19x13 - La Trampa para Bart.flv",
  "Temporada 19/Los Simpsons 19x14 - Con N de Nerd.mp4",
  "Temporada 19/Los Simpsons 19x15 - Humo Sobre la Hija.mp4",
  "Temporada 19/Los Simpsons 19x16 - Papá, No Traiciones.mp4",
  "Temporada 19/Los Simpsons 19x17 - La Vaca del Apocalipsis.mp4",
  "Temporada 19/Los Simpsons 19x18 - En el Festival de Sundance.mp4",
  "Temporada 19/Los Simpsons 19x19 - La Herencia de Mona.mp4",
  "Temporada 19/Los Simpsons 19x20 - Todo sobre Lisa.mp4",
  "Temporada 20/Los Simpsons 20x01 - Pasteles y Persecusiones.mp4",
  "Temporada 20/Los Simpsons 20x02 - Comunicación Perdida.mp4",
  "Temporada 20/Los Simpsons 20x03 - El Doble de Bart.mp4",
  "Temporada 20/Los Simpsons 20x04 - La Casita del Horror XIX.mp4",
  "Temporada 20/Los Simpsons 20x05 - Curvas Peligrosas.mp4",
  "Temporada 20/Los Simpsons 20x06 - Intercambio de Palabras.mp4",
  "Temporada 20/Los Simpsons 20x07 - Mypods y Dinamita.mp4",
  "Temporada 20/Los Simpsons 20x08 - Burns y las Abejas.mp4",
  "Temporada 20/Los Simpsons 20x09 - Lisa La Reina Del Drama.mp4",
  "Temporada 20/Los Simpsons 20x10 - Cambia Mi Vida Por Favor.mp4",
  "Temporada 20/Los Simpsons 20x11 - Cómo Se Ganó La Prueba.mp4",
  "Temporada 20/Los Simpsons 20x12 - No más préstamos.mp4",
  "Temporada 20/Los Simpsons 20x13 - Maggie se Ha Ido.mp4",
  "Temporada 20/Los Simpsons 20x14 - En el Nombre del Abuelo.mp4",
  "Temporada 20/Los Simpsons 20x15 - Boda desastrosa.mp4",
  "Temporada 20/Los Simpsons 20x16 - El Gran Pequeño amor de Moe.mp4",
  "Temporada 20/Los Simpsons 20x17 - Los Buenos, los Tristes y los Drogados.mp4",
  "Temporada 20/Los Simpsons 20x18 - Papá no Sabe Nada.flv",
  `Temporada 20/Los Simpsons 20x19 - Waverly Hills 9-0-2-1-D'Oh.mp4`,
  "Temporada 20/Los Simpsons 20x20 - Cuatro Grandes Mujeres y Manicures.mp4",
  "Temporada 20/Los Simpsons 20x21 - Homerica.mp4",
  "Temporada 21/Los Simpsons 21x00 - Especial 20 Aniversario de Los Simpsons.mp4",
  "Temporada 21/Los Simpsons 21x00 - Especial 20 Aniversario de Los Simpsons.srt",
  "Temporada 21/Los Simpsons 21x01 - Homero El Grande.mp4",
  "Temporada 21/Los Simpsons 21x02 - Bart Obtiene una Z.mp4",
  "Temporada 21/Los Simpsons 21x03 - La Gran Esperanza.mp4",
  "Temporada 21/Los Simpsons 21x04 - La Casita del Horror XX.mp4",
  "Temporada 21/Los Simpsons 21x05 - El Diablo No Usa Nada.mp4",
  "Temporada 21/Los Simpsons 21x06 - Bromas y Legumbres.flv",
  "Temporada 21/Los Simpsons 21x07 - Granjeros y Brujas.mp4",
  "Temporada 21/Los Simpsons 21x08 - Oh hermano, Dónde estás.mp4",
  "Temporada 21/Los Simpsons 21x09 - Jueves con el Abuelo.mp4",
  "Temporada 21/Los Simpsons 21x10 - Erase una Vez en Springfield.mp4",
  "Temporada 21/Los Simpsons 21x11 - Million Dollar Maybe.mp4",
  "Temporada 21/Los Simpsons 21x12 - Campeones Olímpicos.mp4",
  "Temporada 21/Los Simpsons 21x13 - El Color Amarillo.mp4",
  "Temporada 21/Los Simpsons 21x14 - Postales de La Controversia.mp4",
  "Temporada 21/Los Simpsons 21x15 - Robándose la Primera Base.mp4",
  "Temporada 21/Los Simpsons 21x16 - La Historia más Grande Jamás Contada.mp4",
  "Temporada 21/Los Simpsons 21x17 - Historia Americana Excelente.mp4",
  "Temporada 21/Los Simpsons 21x18 - Jefe de Corazones.mp4",
  "Temporada 21/Los Simpsons 21x19 - La Niña y La Ballena.mp4",
  "Temporada 21/Los Simpsons 21x20 - Vigilancia Con Amor.mp4",
  "Temporada 21/Los Simpsons 21x21 - El Blues de La Carta de Moe.mp4",
  "Temporada 21/Los Simpsons 21x22 - El Buen Vecino.mp4",
  "Temporada 21/Los Simpsons 21x23 - Júzgame Con Ternura.mp4",
  "Temporada 22/Los Simpsons 22x01 - El Musical de La Escuela Primaria.mp4",
  "Temporada 22/Los Simpsons 22x02 - Lisa La Prestamista.mp4",
  "Temporada 22/Los Simpsons 22x03 - Bart El Desobediente.mp4",
  "Temporada 22/Los Simpsons 22x04 - La Casita del Horror XXI.mp4",
  "Temporada 22/Los Simpsons 22x05 - Lisa Simpson, Esta No Es Tu Vida.mp4",
  "Temporada 22/Los Simpsons 22x06 - El Tonto Monty.mp4",
  "Temporada 22/Los Simpsons 22x07 - Pobrecita Paloma.mp4",
  "Temporada 22/Los Simpsons 22x08 - El Pleito Antes de Navidad.mp4",
  "Temporada 22/Los Simpsons 22x09 - Donnie, El Gordo.mp4",
  "Temporada 22/Los Simpsons 22x10 - Mamás Que Quisiera Olvidar.mp4",
  "Temporada 22/Los Simpsons 22x11 - El Closet de Moe.mp4",
  "Temporada 22/Los Simpsons 22x12 - Homero, el Padre.mp4",
  "Temporada 22/Los Simpsons 22x13 - Azul y Gris.mp4",
  "Temporada 22/Los Simpsons 22x14 - Papá Enojado La Película.mp4",
  "Temporada 22/Los Simpsons 22x15 - El Cuento del Escorpión.mp4",
  "Temporada 22/Los Simpsons 22x16 - Lindos Sueños de Verano.mp4",
  "Temporada 22/Los Simpsons 22x17 - Amar es Estrangular.mp4",
  "Temporada 22/Los Simpsons 22x18 - La Gran Simpsina.mp4",
  "Temporada 22/Los Simpsons 22x19 - Las Verdaderas Esposas del Gordo Tony.mp4",
  "Temporada 22/Los Simpsons 22x20 - Homero Manos de Tijera.mp4",
  "Temporada 22/Los Simpsons 22x21 - 500 Llaves.mp4",
  "Temporada 22/Los Simpsons 22x22 - El Atrapa Mentiras de Ned.mp4",
  `Temporada 23/Los Simpsons 23x01 - El Halcón y el Hombre D'Oh.flv`,
  "Temporada 23/Los Simpsons 23x02 - Bart se detiene a oler a los Roosevelts.mp4",
  "Temporada 23/Los Simpsons 23x03 - La Casita del Horror XXII.mp4",
  "Temporada 23/Los Simpsons 23x04 - Eres Reemplazable.mp4",
  "Temporada 23/Los Simpsons 23x05 - La Esposa Aficionada.mp4",
  "Temporada 23/Los Simpsons 23x06 - La Mision del Libro.mp4",
  "Temporada 23/Los Simpsons 23x07 - El Hombre de los pantalones de franela azul.mp4",
  "Temporada 23/Los Simpsons 23x08 - La Solución del 10 por ciento.mp4",
  "Temporada 23/Los Simpsons 23x09 - Fiestas de un Futuro Pasado.mp4",
  "Temporada 23/Los Simpsons 23x10 - Politicamente inepto, con Homero Simpson.mp4",
  `Temporada 23/Los Simpsons 23x11 - La Cadena D'oh-cial.mp4`,
  "Temporada 23/Los Simpsons 23x12 - Moe de Mendigo a Millonario.mp4",
  "Temporada 23/Los Simpsons 23x13 - La Hija También se Ilusiona.mp4",
  "Temporada 23/Los Simpsons 23x14 - Por Fin Se Van (Episodio 500).mkv",
  "Temporada 23/Los Simpsons 23x15 - Salida por el Kwik-E-Mart.mp4",
  "Temporada 23/Los Simpsons 23x16 - Como moje a su Madre.mp4",
  "Temporada 23/Los Simpsons 23x17 - Ellos, Robot.mp4",
  "Temporada 23/Los Simpsons 23x18 - Cuidado con Bart.mp4",
  "Temporada 23/Los Simpsons 23x19 - Algo Muy Divertido Que Bart No Volverá a Hacer.mp4",
  "Temporada 23/Los Simpsons 23x20 - El Espia Que Me Enseño.mp4",
  "Temporada 23/Los Simpsons 23x21 - El Matrimonio de Ned y Edna.mp4",
  "Temporada 23/Los Simpsons 23x22 - Lisa y Lady Gaga.mp4",
  "Temporada 24/Los Simpsons 24x01 - Rio de Aguardiente.mp4",
  "Temporada 24/Los Simpsons 24x02 - La Casita del Horror XXIII.mp4",
  "Temporada 24/Los Simpsons 24x03 - Aventuras Para Tener un Bebé.mp4",
  "Temporada 24/Los Simpsons 24x04 - Donde Estás Abuelo.mp4",
  "Temporada 24/Los Simpsons 24x05 - Los Mafiosos.mp4",
  "Temporada 24/Los Simpsons 24x06 - Un Árbol Crece en Springfield.mp4",
  "Temporada 24/Los Simpsons 24x07 - El Día que la Tierra fue Cool.mp4",
  "Temporada 24/Los Simpsons 24x08 - A Mi Perro, Con Amor.mkv",
  "Temporada 24/Los Simpsons 24x09 - Homero Ya Esta Preparado.mp4",
  "Temporada 24/Los Simpsons 24x10 - Una Prueba Antes de Intentarlo.mp4",
  "Temporada 24/Los Simpsons 24x11 - Cambio De Tutor.mp4",
  "Temporada 24/Los Simpsons 24x12 - El Amor es un Asunto Peliagudo.mp4",
  "Temporada 24/Los Simpsons 24x13 - Casi Kirk.mp4",
  "Temporada 24/Los Simpsons 24x14 - El Abuelo Glamoroso.mp4",
  "Temporada 24/Los Simpsons 24x15 - El Ojo Negro.mp4",
  "Temporada 24/Los Simpsons 24x16 - La Corte Del Caballero de la Noche.mp4",
  "Temporada 24/Los Simpsons 24x17 - Lo Que Quieren las Mujeres Animadas.mp4",
  "Temporada 24/Los Simpsons 24x18 - Tiempos Violentos en el Púlpito.mp4",
  "Temporada 24/Los Simpsons 24x19 - El Negocio Del Whisky.mp4",
  "Temporada 24/Los Simpsons 24x20 - El Fabuloso Farsante.mp4",
  "Temporada 24/Los Simpsons 24x21 - La Saga de Carl.mp4",
  "Temporada 24/Los Simpsons 24x22 - Peligros en un tren.mp4",
  "Temporada 25/Los Simpsons 25x01 - Homerland (Subs).mp4",
  "Temporada 25/Los Simpsons 25x01 - Homerland (Subs).srt",
  "Temporada 25/Los Simpsons 25x02 - Treehouse of Horror XXIV (Subs).mp4",
  "Temporada 25/Los Simpsons 25x02 - Treehouse of Horror XXIV (Subs).srt",
  "Temporada 25/Los Simpsons 25x03 - Four Regrettings and a Funeral (Subs).mp4",
  "Temporada 25/Los Simpsons 25x03 - Four Regrettings and a Funeral (Subs).srt",
  "Temporada 25/Los Simpsons 25x04 - YOLO (Subs).flv",
  "Temporada 25/Los Simpsons 25x04 - YOLO (Subs).srt",
  "Temporada 25/Los Simpsons 25x05 - Labor Pains (Subs).flv",
  "Temporada 25/Los Simpsons 25x05 - Labor Pains (Subs).srt",
  "Temporada 25/Los Simpsons 25x06 - The Kid Is All Right (Subs).mp4",
  "Temporada 25/Los Simpsons 25x06 - The Kid Is All Right (Subs).srt",
  "Temporada 25/Los Simpsons 25x07 - Yellow Subterfuge (Subs).mp4",
  "Temporada 25/Los Simpsons 25x07 - Yellow Subterfuge (Subs).srt",
  "Temporada 25/Los Simpsons 25x08 - White Christmas Blues (Subs).mp4",
  "Temporada 25/Los Simpsons 25x08 - White Christmas Blues (Subs).srt",
  "Temporada 25/Los Simpsons 25x09 - Steal This Episode (Subs).mp4",
  "Temporada 25/Los Simpsons 25x09 - Steal This Episode (Subs).srt",
  "Temporada 25/Los Simpsons 25x10 - Married To The Blob (Subs).mp4",
  "Temporada 25/Los Simpsons 25x10 - Married To The Blob (Subs).srt",
];
